name: Deploy

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Format Check
        run: deno fmt --check

      - name: Lint Check
        run: deno lint

      - name: Type Check
        run: deno check **/*.ts **/*.tsx

      - name: Run Tests
        run: |
          if [ -n "$(find . -name '*_test.ts')" ]; then
            deno test --allow-all
          else
            echo "No deno test modules found, skipping tests."
          fi

  deploy:
    name: Deploy to Deno
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Build Step
        run: deno task build

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "thehighlandernetwork"
          entrypoint: "main.ts"
          root: "."
